### ISSUE TITLE
Most of the image links in the examples in the readme are broken links. Seems like the images have been taken down from the host site or something similar. Yes your right working on solving this quick !

### ISSUE THREAD

**Issue by jams77** [ellerbrock/open-source-badges#13]
Most of the image links in the examples in the readme are broken links. Seems like the images have been taken down from the host site or something similar.

__Originally posted by @StjerneIdioten in https://github.com/ellerbrock/open-source-badges/issues/12__

**Comment by jams77** [comment]
Need help for non binary human !!

**Comment by Bhupesh-V** [comment]
> Need help for non binary human !!

You can refer to the images already present in the [badges](https://github.com/ellerbrock/open-source-badges/tree/master/badges) folder.
For example, here is the [bash ❤️ #! ](https://raw.githubusercontent.com/ellerbrock/open-source-badges/master/badges/bash-v1/bash-150x25.png) badge

**Comment by ellerbrock** [comment]
Hi,

thanks for the feedback.
The issue came from an expired SSL certificate which i just renewed.
Should be fixed by now.

Cheers,
Maik
